from . import base_archive
from . import library_member
from . import library_book
from . import library_book_rent
from . import library_book_rent_statistics
from . import library_book_categ
from . import library_book_copy
from . import res_partner_inherit
from . import res_config_settings_inherit